### ISSUE TITLE
Can we please have a 32bit windows version?

### ISSUE THREAD

**Issue by kimtang** [KxSystems/solace#160]
Currently only 32bit is a not on-demand version.

**Comment by sshanks-kx** [comment]
Thanks for raising a request. 
Will look into it & update this ticket.

Thanks

**Comment by kimtang** [comment]
I was able to compile kdbsolace in w32. So it is doable. Of course there is a small effort to make the install.bat more generic.

> q sol_version.q
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
w32/ 16()core 4095MB  #### NONEXPIRE

### API version info
solVersion| 7.14.0.8
solDate   | Jun  3 2020 15:59:17
solVariant| Win32_opt - C SDK

**Comment by sshanks-kx** [comment]
Added to latest release. https://github.com/KxSystems/solace/releases/tag/1.1.0
