### ISSUE TITLE
Consideration of receiving 'text' messages

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/solace#163]
Ref: https://docs.solace.com/Solace-JMS-API/Creating-JMS-Compatible-Msgs.htm#TextMess

Try and observe effects of send/receive with string/text type message. See if we can automatically switch if binary attachment of received msg would fail on this occurance.

**Comment by sshanks-kx** [comment]
Using solace cloud
Mapping topic to queue, subscribing to queue
Pub a message into topic using 'try me' feature of solace cloud....

q client gets **\034\017Hello world!\000** when publishing **Hello world!**

**Comment by sshanks-kx** [comment]
Recreated different result using https://github.com/sshanks-kx/market-data-simulator

Changed src/main/java/com/marketdatasimulator/Main.java to use a TextMessage instead 

```
                    /*
                    BytesMessage message = session.createBytesMessage();
                    message.writeBytes(textMessage.getBytes());
                    */
                    TextMessage message = session.createTextMessage();
                    message.setText(textMessage);
```

**Comment by sshanks-kx** [comment]
getbinaryattachmentptr also return error - related info

https://docs.solace.com/Solace-JMS-API/Creating-JMS-Compatible-Msgs.htm#TextMess
	These samples require the JMS connection factory setting text-msg-xml-payload to be set to false, which specifies that the TextMessage string is set/get in the messageʼs binary attachment.

https://stackoverflow.com/questions/48647787/invald-characters-at-start-of-message-from-solace-mq
	For a JMS TextMessage it will be in the XML content part of the message (unless you have the JMS connection factory setting text-msg-xml-payload to be set to false)

**Comment by sshanks-kx** [comment]
Doing this with JMS client allows getBinaryAttachmentPtr and getBinaryAttachmentString to work
connectionFactory.setXmlPayload(false);

**Comment by sshanks-kx** [comment]
1. JMS Text Message with 'connectionFactory.setXmlPayload(false);'
* solClient_msg_getBinaryAttachmentPtr works but non-text data
* solClient_msg_getBinaryAttachmentString works 
* solClient_msg_getXmlPtr fails

2. JMS Text Message with default XML payload
* solClient_msg_getBinaryAttachmentPtr fails
* solClient_msg_getBinaryAttachmentString fails 
* solClient_msg_getXmlPtr works

3. Text Message from 'try-me' on Solace Cloud
* solClient_msg_getBinaryAttachmentPtr works (but with binary data before/after string)
* solClient_msg_getBinaryAttachmentString works 
* solClient_msg_getXmlPtr fails

4. Binary message from 'try-me' on Solace Cloud
* solClient_msg_getBinaryAttachmentPtr works
* solClient_msg_getBinaryAttachmentString fails 
* solClient_msg_getXmlPtr fails

**Comment by sshanks-kx** [comment]
Requested info from Solace on advised actions

**Comment by sshanks-kx** [comment]
Potential pseudocode for change

```
If ( (res= solClient_msg_getXmlPtr(msg, &dataPtr, &dataSize)) == SOLCLIENT_OK) {
    // Success – use bufptr_p as a const char*
}
else if ( (res = solClient_msg_getBinaryAttachmentString(... )) == SOLCLIENT_OK) {
    // Success - use the char* bufptr_p
}
else if ( (res = solClient_msg_getBinaryAttachmentMap(... )) == SOLCLIENT_OK) {
    // error – full serialization binding required
}
else if ( (res = solClient_msg_getBinaryAttachmentStream(... )) == SOLCLIENT_OK) {
    // error – full serialization binding required
}
else if ( (res = solClient_msg_getBinaryAttachmentPtr(... )) == SOLCLIENT_OK) {
    // Success – use bufptr_p as a void*
}
else {
    // Error – unknown msgtype
}
```

**Comment by sshanks-kx** [comment]
Solace confirmed what was seen & proposed solution will have issues i.e. binary payload area in solace message is also used for their encoded solace messages (e.g. solace string), so a user sending binary messages that matched certain patterns could be wrongly misinterpreted as a solace typed message.
User api may have to choose the type of message they want to attempt to read as it cant be determined automatically.

**Comment by TKTheTechie** [comment]
Thanks Simon. Yes - what a possible workaround is will be for the user to optionally specify the payload type to force deserialization to that type. The likelihood of sending a string type that will get misinterpreted is extremely low (1 in 16 M to be exact) and I’ve confirmed with R&D that this hasn’t been reported yet by any of our customers. That being said it is worth documenting as an issue in the README if that makes sense. We also have it on the backlog on our side

**Comment by sshanks-kx** [comment]
Id prefer not to have the general solution that might get misinterpreted due to 
* may not just the string type (I didnt try the rest)
* may suddenly crash or corrupt data when it matches once on a stream of data (e.g. 3rd party serialisation/compression/encryption lib) - which may also be very difficult to find out if it was actually this problem after the crash/corruption occurs (e.g. crashes/corrupts once within millions of received msgs)
* given we dont know all encyption/compression/serialisation formats (+ ones being developed now + in-house formats) - so we prob dont know the likehood of hitting the issue. It just takes 1 user to have a similar format (or algorithm were match can occur) were it can never be used (100% of all msgs have a problem) or increased their likehood substantially. All prev users may also not have been doing pure binary sub with non-binary pub (given prev point also - theres a chance they may not have detected it as root cause if it did).
* I (or any contributer) will have to spend some time looking at alternative solution (e.g. subscribe/subscribeString/subscribeXML or values passed in on init or option were they accept liability for misinterpretation or another). Will update with potential solution when this is done once they been weighed-up (given the various advantages/disadvantages for each).

**Comment by sshanks-kx** [comment]
Handling of binary/xml/string added to https://github.com/KxSystems/solace/releases/tag/1.1.0
