### ISSUE TITLE
Incorrect return code and message if failed to connect 

### ISSUE THREAD

**Issue by kiniv** [KxSystems/solace#168]
If solClient_session_connect failed, the return code to print error message and return back to q is used from solClient_session_create.

**Comment by kiniv** [comment]
Thanks @sshanks-kx for quick fix!

**Comment by sshanks-kx** [comment]
Fix now present in release 1.1.1 https://github.com/KxSystems/solace/releases/tag/1.1.1
Please hit the watch button at the top of the page to be notified of further releases/etc & click the star button on the repo if you find the project useful.

Thanks
